apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cmk-workload5-pod
  name: cmk-workload5-pod
# Consumed by mutating webhook
  annotations:
    cmk.intel.com/mutate: "true" # accepted values to trigger mutation: "true", "True", "1"
  namespace: cmk-namespace
spec:
  selector:
   matchLabels:
    app: cmk-workload5-pod
  replicas: 0
  template:
    metadata:
      labels:
        app: cmk-workload5-pod
    spec:
     serviceAccountName: cmk-serviceaccount
     containers:
      - name: cmk-isolate-shared-workload5
        image: hrabhijith2/play:shared
        imagePullPolicy: Always
        ports:
         - containerPort: 5003
           hostPort: 5003
        volumeMounts:
         - name: tmp
           mountPath: "/tmp"
        securityContext:
         allowPrivilegeEscalation: true
         readOnlyRootFilesystem: true
         runAsNonRoot: false
         privileged: true
         capabilities:
          drop:
           - all
     volumes:
      - hostPath:
         path: "/tmp"
        name: tmp
